// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_button_parent
global.__objectDepths[1] = -999; // obj_ad
global.__objectDepths[2] = -1; // seqcontrol
global.__objectDepths[3] = -1; // obj_fillframes
global.__objectDepths[4] = -1; // obj_aniblankdcselect
global.__objectDepths[5] = -1; // obj_anienddotscolorselect
global.__objectDepths[6] = -100; // controller
global.__objectDepths[7] = -1; // obj_shakingsdev
global.__objectDepths[8] = -1; // obj_aniblankoffselect
global.__objectDepths[9] = -1000; // obj_cursor
global.__objectDepths[10] = 0; // settingscontrol
global.__objectDepths[11] = -1; // obj_anicolordcselect
global.__objectDepths[12] = -1; // obj_aniwaveoffselect
global.__objectDepths[13] = -1; // obj_aniwaveamp
global.__objectDepths[14] = -1; // obj_anifunc
global.__objectDepths[15] = -5; // oDropDown
global.__objectDepths[16] = -1; // obj_shake
global.__objectDepths[17] = -1; // obj_anirepselect
global.__objectDepths[18] = -1; // obj_anicoloroffselect
global.__objectDepths[19] = -1; // obj_blanktselect
global.__objectDepths[20] = -1; // obj_blankfreqselect
global.__objectDepths[21] = -1; // obj_blankoffselect
global.__objectDepths[22] = -1; // obj_funcblank
global.__objectDepths[23] = -1; // obj_blankingdcselect
global.__objectDepths[24] = -1; // obj_blankblendmode
global.__objectDepths[25] = 0; // obj_loadingbar
global.__objectDepths[26] = -2; // obj_enddots
global.__objectDepths[27] = -1; // obj_anienable
global.__objectDepths[28] = -1; // obj_anicolorselect_2
global.__objectDepths[29] = -2; // obj_b_dot
global.__objectDepths[30] = -1; // obj_anicolorselect_1
global.__objectDepths[31] = -1; // obj_colorselect_2
global.__objectDepths[32] = -2; // obj_c_solid
global.__objectDepths[33] = -1; // obj_enddotscolorselect
global.__objectDepths[34] = -1; // obj_anishakingsdev
global.__objectDepths[35] = -1; // obj_resettrans
global.__objectDepths[36] = -2; // obj_rainbow
global.__objectDepths[37] = -2; // obj_c_func
global.__objectDepths[38] = -2; // obj_blankabsrel
global.__objectDepths[39] = -2; // obj_c_dash
global.__objectDepths[40] = -1; // obj_colorblendmode
global.__objectDepths[41] = -2; // obj_b_solid
global.__objectDepths[42] = -2; // obj_b_dash
global.__objectDepths[43] = -1; // obj_funcbselect
global.__objectDepths[44] = -1; // obj_funcgselect
global.__objectDepths[45] = -2; // obj_b_dotsolid
global.__objectDepths[46] = -1; // obj_funcvselect
global.__objectDepths[47] = -2; // obj_b_func
global.__objectDepths[48] = -1; // obj_funchselect
global.__objectDepths[49] = -1; // obj_funcsselect
global.__objectDepths[50] = -1; // obj_colorcopyfromani
global.__objectDepths[51] = -1; // obj_coloroffselect
global.__objectDepths[52] = -1; // obj_colorcopytoani
global.__objectDepths[53] = -2; // obj_c_gradient
global.__objectDepths[54] = -1; // obj_wavetselect
global.__objectDepths[55] = -2; // obj_text
global.__objectDepths[56] = -1; // obj_funcxselect
global.__objectDepths[57] = -1; // obj_colorfreqselect
global.__objectDepths[58] = -1; // obj_colortselect
global.__objectDepths[59] = -2; // obj_colorabsrel
global.__objectDepths[60] = -1; // obj_funcrselect
global.__objectDepths[61] = -2; // obj_s_wave
global.__objectDepths[62] = -1; // obj_colordcselect
global.__objectDepths[63] = -2; // obj_s_circle
global.__objectDepths[64] = -2; // obj_reapply_blank
global.__objectDepths[65] = -1; // obj_funcyselect
global.__objectDepths[66] = -2; // obj_func
global.__objectDepths[67] = -2; // obj_s_line
global.__objectDepths[68] = -2; // obj_hershey
global.__objectDepths[69] = -2; // obj_scope
global.__objectDepths[70] = -2; // obj_curve
global.__objectDepths[71] = -2; // obj_s_free
global.__objectDepths[72] = -1; // obj_waveoffselect
global.__objectDepths[73] = -2; // obj_reapply_color
global.__objectDepths[74] = -1; // obj_funcpointselect
global.__objectDepths[75] = -1; // obj_waveampselect
global.__objectDepths[76] = -1; // obj_colorselect_1
global.__objectDepths[77] = -2; // obj_select
global.__objectDepths[78] = 0; // obj_colorselectparent
global.__objectDepths[79] = -2; // obj_onionskin
global.__objectDepths[80] = -2; // obj_grid
global.__objectDepths[81] = 0; // obj_colorselectparentani
global.__objectDepths[82] = -1; // obj_addmarker
global.__objectDepths[83] = -2; // obj_totimeline
global.__objectDepths[84] = -1; // obj_exportproject
global.__objectDepths[85] = -1; // obj_saveproject
global.__objectDepths[86] = -1; // obj_sendtoeditor
global.__objectDepths[87] = -1; // obj_audioshift
global.__objectDepths[88] = -2; // obj_save
global.__objectDepths[89] = -1; // obj_loadaudio
global.__objectDepths[90] = -1; // obj_loadproject
global.__objectDepths[91] = -1; // obj_openeditor
global.__objectDepths[92] = -2; // obj_length
global.__objectDepths[93] = -2; // obj_export
global.__objectDepths[94] = -1; // obj_tooltip
global.__objectDepths[95] = -1; // obj_invertx
global.__objectDepths[96] = -1; // obj_inverty
global.__objectDepths[97] = -2; // obj_update
global.__objectDepths[98] = -2; // obj_profiles
global.__objectDepths[99] = -1; // obj_addprofile
global.__objectDepths[100] = -1; // obj_seqloop
global.__objectDepths[101] = -2; // obj_dacscan
global.__objectDepths[102] = -2; // obj_dacname
global.__objectDepths[103] = -1; // obj_volume
global.__objectDepths[104] = -2; // obj_projectors
global.__objectDepths[105] = -1; // obj_colorscale
global.__objectDepths[106] = -1; // obj_scanrate
global.__objectDepths[107] = -1; // obj_onlyblanking
global.__objectDepths[108] = 0; // obj_comingsoon
global.__objectDepths[109] = -1; // obj_maxdwell_blank
global.__objectDepths[110] = -1; // obj_blueshift
global.__objectDepths[111] = -1; // obj_greenshift
global.__objectDepths[112] = -1; // obj_optimize
global.__objectDepths[113] = -1; // obj_autoupdate
global.__objectDepths[114] = -2; // obj_addblindzone
global.__objectDepths[115] = -2; // obj_dacs
global.__objectDepths[116] = -2; // obj_fps
global.__objectDepths[117] = -2; // obj_playcontrols
global.__objectDepths[118] = -2; // obj_toseq
global.__objectDepths[119] = -1; // obj_maxdwell
global.__objectDepths[120] = -2; // obj_import
global.__objectDepths[121] = -2; // obj_load
global.__objectDepths[122] = -2; // obj_laseron
global.__objectDepths[123] = -2; // obj_help
global.__objectDepths[124] = -2; // obj_format
global.__objectDepths[125] = -2; // obj_projection
global.__objectDepths[126] = -2; // obj_options
global.__objectDepths[127] = -1; // obj_blankshift
global.__objectDepths[128] = -1; // obj_redshift
global.__objectDepths[129] = -1; // obj_samplingrate
global.__objectDepths[130] = 0; // obj_testframe
global.__objectDepths[131] = -2; // obj_mute
global.__objectDepths[132] = 0; // obj_projectionzones
global.__objectDepths[133] = -1; // obj_playbackspeed
global.__objectDepths[134] = -1; // obj_largepreview
global.__objectDepths[135] = -1; // obj_clearmarkers


global.__objectNames[0] = "obj_button_parent";
global.__objectNames[1] = "obj_ad";
global.__objectNames[2] = "seqcontrol";
global.__objectNames[3] = "obj_fillframes";
global.__objectNames[4] = "obj_aniblankdcselect";
global.__objectNames[5] = "obj_anienddotscolorselect";
global.__objectNames[6] = "controller";
global.__objectNames[7] = "obj_shakingsdev";
global.__objectNames[8] = "obj_aniblankoffselect";
global.__objectNames[9] = "obj_cursor";
global.__objectNames[10] = "settingscontrol";
global.__objectNames[11] = "obj_anicolordcselect";
global.__objectNames[12] = "obj_aniwaveoffselect";
global.__objectNames[13] = "obj_aniwaveamp";
global.__objectNames[14] = "obj_anifunc";
global.__objectNames[15] = "oDropDown";
global.__objectNames[16] = "obj_shake";
global.__objectNames[17] = "obj_anirepselect";
global.__objectNames[18] = "obj_anicoloroffselect";
global.__objectNames[19] = "obj_blanktselect";
global.__objectNames[20] = "obj_blankfreqselect";
global.__objectNames[21] = "obj_blankoffselect";
global.__objectNames[22] = "obj_funcblank";
global.__objectNames[23] = "obj_blankingdcselect";
global.__objectNames[24] = "obj_blankblendmode";
global.__objectNames[25] = "obj_loadingbar";
global.__objectNames[26] = "obj_enddots";
global.__objectNames[27] = "obj_anienable";
global.__objectNames[28] = "obj_anicolorselect_2";
global.__objectNames[29] = "obj_b_dot";
global.__objectNames[30] = "obj_anicolorselect_1";
global.__objectNames[31] = "obj_colorselect_2";
global.__objectNames[32] = "obj_c_solid";
global.__objectNames[33] = "obj_enddotscolorselect";
global.__objectNames[34] = "obj_anishakingsdev";
global.__objectNames[35] = "obj_resettrans";
global.__objectNames[36] = "obj_rainbow";
global.__objectNames[37] = "obj_c_func";
global.__objectNames[38] = "obj_blankabsrel";
global.__objectNames[39] = "obj_c_dash";
global.__objectNames[40] = "obj_colorblendmode";
global.__objectNames[41] = "obj_b_solid";
global.__objectNames[42] = "obj_b_dash";
global.__objectNames[43] = "obj_funcbselect";
global.__objectNames[44] = "obj_funcgselect";
global.__objectNames[45] = "obj_b_dotsolid";
global.__objectNames[46] = "obj_funcvselect";
global.__objectNames[47] = "obj_b_func";
global.__objectNames[48] = "obj_funchselect";
global.__objectNames[49] = "obj_funcsselect";
global.__objectNames[50] = "obj_colorcopyfromani";
global.__objectNames[51] = "obj_coloroffselect";
global.__objectNames[52] = "obj_colorcopytoani";
global.__objectNames[53] = "obj_c_gradient";
global.__objectNames[54] = "obj_wavetselect";
global.__objectNames[55] = "obj_text";
global.__objectNames[56] = "obj_funcxselect";
global.__objectNames[57] = "obj_colorfreqselect";
global.__objectNames[58] = "obj_colortselect";
global.__objectNames[59] = "obj_colorabsrel";
global.__objectNames[60] = "obj_funcrselect";
global.__objectNames[61] = "obj_s_wave";
global.__objectNames[62] = "obj_colordcselect";
global.__objectNames[63] = "obj_s_circle";
global.__objectNames[64] = "obj_reapply_blank";
global.__objectNames[65] = "obj_funcyselect";
global.__objectNames[66] = "obj_func";
global.__objectNames[67] = "obj_s_line";
global.__objectNames[68] = "obj_hershey";
global.__objectNames[69] = "obj_scope";
global.__objectNames[70] = "obj_curve";
global.__objectNames[71] = "obj_s_free";
global.__objectNames[72] = "obj_waveoffselect";
global.__objectNames[73] = "obj_reapply_color";
global.__objectNames[74] = "obj_funcpointselect";
global.__objectNames[75] = "obj_waveampselect";
global.__objectNames[76] = "obj_colorselect_1";
global.__objectNames[77] = "obj_select";
global.__objectNames[78] = "obj_colorselectparent";
global.__objectNames[79] = "obj_onionskin";
global.__objectNames[80] = "obj_grid";
global.__objectNames[81] = "obj_colorselectparentani";
global.__objectNames[82] = "obj_addmarker";
global.__objectNames[83] = "obj_totimeline";
global.__objectNames[84] = "obj_exportproject";
global.__objectNames[85] = "obj_saveproject";
global.__objectNames[86] = "obj_sendtoeditor";
global.__objectNames[87] = "obj_audioshift";
global.__objectNames[88] = "obj_save";
global.__objectNames[89] = "obj_loadaudio";
global.__objectNames[90] = "obj_loadproject";
global.__objectNames[91] = "obj_openeditor";
global.__objectNames[92] = "obj_length";
global.__objectNames[93] = "obj_export";
global.__objectNames[94] = "obj_tooltip";
global.__objectNames[95] = "obj_invertx";
global.__objectNames[96] = "obj_inverty";
global.__objectNames[97] = "obj_update";
global.__objectNames[98] = "obj_profiles";
global.__objectNames[99] = "obj_addprofile";
global.__objectNames[100] = "obj_seqloop";
global.__objectNames[101] = "obj_dacscan";
global.__objectNames[102] = "obj_dacname";
global.__objectNames[103] = "obj_volume";
global.__objectNames[104] = "obj_projectors";
global.__objectNames[105] = "obj_colorscale";
global.__objectNames[106] = "obj_scanrate";
global.__objectNames[107] = "obj_onlyblanking";
global.__objectNames[108] = "obj_comingsoon";
global.__objectNames[109] = "obj_maxdwell_blank";
global.__objectNames[110] = "obj_blueshift";
global.__objectNames[111] = "obj_greenshift";
global.__objectNames[112] = "obj_optimize";
global.__objectNames[113] = "obj_autoupdate";
global.__objectNames[114] = "obj_addblindzone";
global.__objectNames[115] = "obj_dacs";
global.__objectNames[116] = "obj_fps";
global.__objectNames[117] = "obj_playcontrols";
global.__objectNames[118] = "obj_toseq";
global.__objectNames[119] = "obj_maxdwell";
global.__objectNames[120] = "obj_import";
global.__objectNames[121] = "obj_load";
global.__objectNames[122] = "obj_laseron";
global.__objectNames[123] = "obj_help";
global.__objectNames[124] = "obj_format";
global.__objectNames[125] = "obj_projection";
global.__objectNames[126] = "obj_options";
global.__objectNames[127] = "obj_blankshift";
global.__objectNames[128] = "obj_redshift";
global.__objectNames[129] = "obj_samplingrate";
global.__objectNames[130] = "obj_testframe";
global.__objectNames[131] = "obj_mute";
global.__objectNames[132] = "obj_projectionzones";
global.__objectNames[133] = "obj_playbackspeed";
global.__objectNames[134] = "obj_largepreview";
global.__objectNames[135] = "obj_clearmarkers";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for